version: 2
jobs:
  build:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt      
      - run:
          name: create gazetteer
          command: |
            . venv/bin/activate
            python3 create_gazetteer_from_wikidata.py         
      - run:
          name: run tests
          command: echo "will write testing code later"
