version: 2
jobs:
    build:
        docker:
            - image: python:latest
        steps:
            - checkout
            - run:
                name: Update System Packages
                command: apt-get update
            - run:
                name: install system dependencies
                command: apt-get install zip
            - run:
                name: install dependencies
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt      
            - run:
                name: create gazetteer
                command: |
                    . venv/bin/activate
                    python3 create_gazetteer_from_wikidata.py
            - run:
                name: create set of place titles
                command: |
                    . venv/bin/activate
                    python3 create_place_titles.py   
            - run:
                name: run tests
                command: echo "will write tests later"
            - run:
                name: Install AWS CLI
                command: pip install awscli --upgrade
            - run:
                name: Zip Pickled Python Set
                command: zip -r /tmp/place_titles.pickle.zip /tmp/place_titles.pickle
            - run:
                name: Zip Gazetteer
                command: zip -r /tmp/wikidata-gazetteer.tsv.zip /tmp/wikidata-gazetteer.tsv
            - run:
                name: Copy Pickled Set into S3 Bucket
                command: aws s3 cp /tmp/place_titles.pickle.zip s3://firstdraftgis/place_titles.pickle.zip
            - run:
                name: Copy Gazetteer into S3 Bucket
                command: aws s3 cp /tmp/wikidata-gazetteer.tsv.zip s3://firstdraftgis/wikidata-gazetteer.tsv.zip
